#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Linting and building your project before committing'

npm run lint || (
  echo 'ESLint check failed. Fix the issues above, add changes, and try committing again.'
  false
)

echo 'Trying to build the project before committing...'

npm run build || (
  echo 'Build failed. Fix the build errors above, add changes, and try committing again.'
  false
)

echo '✅ All checks passed. Proceeding with commit.'
